version: '3.8'

services:
  erp-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: college_erp_app
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/college_erp
      - JWT_SECRET=college_erp_super_secret_jwt_key_2026
    depends_on:
      - mongo
    restart: always

  mongo:
    image: mongo:7.0
    container_name: college_erp_db
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    restart: always

volumes:
  mongo_data:
